# Generated by Django 4.1.3 on 2022-12-11 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0002_coach_coachclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='workout_manager.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='workout_manager.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('W', 'Weight'), ('T', 'Time'), ('C', 'Custom')], max_length=1)),
                ('status', models.CharField(choices=[('D', 'Done'), ('P', 'Partially'), ('U', 'Undone'), ('W', 'Waiting')], default='W', max_length=1)),
                ('load', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('repetitions_number', models.IntegerField(blank=True)),
                ('series_number', models.IntegerField(blank=True)),
                ('duration', models.DurationField(blank=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_manager.training')),
            ],
        ),
    ]
