# Generated by Django 4.1.3 on 2022-12-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0004_alter_exercise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='title',
            field=models.CharField(default='FBW - Poniedziałek', max_length=255),
            preserve_default=False,
        ),
    ]
