# Generated by Django 4.1.3 on 2023-01-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0006_alter_training_client_alter_training_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='load',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetitions_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='series_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
