# Generated by Django 4.1.3 on 2023-01-29 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0010_alter_trainingcomment_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 1, 29)),
            preserve_default=False,
        ),
    ]
