# Generated by Django 4.1.3 on 2023-01-30 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0011_trainingcomment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workout_manager.coachclient')),
            ],
        ),
    ]
