# Generated by Django 4.1.5 on 2023-01-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0013_commentimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentImage',
            new_name='CommentFile',
        ),
    ]
