# Generated by Django 4.1.5 on 2023-01-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0014_rename_commentimage_commentfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentfile',
            old_name='image',
            new_name='file',
        ),
    ]
