# Generated by Django 4.1.5 on 2023-01-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0015_rename_image_commentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workout_manager.trainingcomment'),
        ),
    ]
