# Generated by Django 4.1.5 on 2023-02-01 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0016_alter_commentfile_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.FileField(upload_to='comments/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='trainingcomment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
