# Generated by Django 4.1.5 on 2023-02-07 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_manager', '0017_alter_commentfile_file_alter_trainingcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfile',
            name='file',
            field=models.FileField(upload_to='comments/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4', 'jpeg'])]),
        ),
    ]
